function v6(a) return a end

return {
    Grenade = {
        class = "Grenade", 
        type = "bomb", 
        protoBolt = v6("ProtoGrenade"), 
        range = 180, 
        loArcSpeed = 140, 
        loArcGravity = 30, 
        hiArcSpeed = 150, 
        hiArcGravity = 190, 
        apRadius = 3.2, 
        apForce = 160, 
        heRadius = 4, 
        heForce = 50, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 40, 
        avScale = 28, 
        reloadTime = 5, 
        sticky = false, 
        explOnContact = false, 
        fuseTime = 3, 
        carryMax = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 3.5, 
                apForce = 170, 
                heRadius = 4.5, 
                heForce = 56, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 44.8, 
                avScale = 34
            }
        }
    }, 
    Bomb = {
        class = "Bomb", 
        type = "bomb", 
        protoBolt = v6("ProtoBomb"), 
        range = 60, 
        loArcSpeed = 140, 
        loArcGravity = 30, 
        hiArcSpeed = 150, 
        hiArcGravity = 190, 
        apRadius = 4.2, 
        apForce = 75, 
        heRadius = 3, 
        heForce = 50, 
        frForce = 100, 
        frForceMin = 30, 
        frRadius = 10, 
        avScale = math.random(10, 20) / 10, 
        aScale = math.random(30, 45) / 100, 
        sticky = false, 
        explOnContact = true, 
        reloadTime = 1, 
        carryMax = 6, 
        shopRank = 1, 
        shopCost = 300, 
        shopQuantity = "unlimited", 
        shopDescr = "Bomb, Standard", 
        shopTip = "Standard issue bomb. Somewhat effective against armor and players, but short reload delay and explodes on contact.", 
        upgradeList = {}, 
        upgrades = {}
    }, 
    C4 = {
        class = "C4", 
        type = "bomb", 
        protoBolt = v6("ProtoDynamite"), 
        range = 40, 
        loArcSpeed = 100, 
        loArcGravity = 100, 
        hiArcSpeed = 150, 
        hiArcGravity = 220, 
        apRadius = 5.3, 
        apForce = 255, 
        heRadius = 15, 
        heForce = 224, 
        frForce = 100, 
        frForceMin = 30, 
        frRadius = 7, 
        avScale = 50, 
        reloadTime = 1.3, 
        fuseTime = 3, 
        sticky = true, 
        lifeTime = 135, 
        explOnContact = false, 
        carryMax = 8, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Fuseless", 
                fuseTime = false
            }
        }
    }, 
    Smoke = {
        class = "Smoke", 
        type = "bomb", 
        protoBolt = v6("ProtoSmoke"), 
        smokebomb = true, 
        range = 200, 
        loArcSpeed = 140, 
        loArcGravity = 30, 
        hiArcSpeed = 150, 
        hiArcGravity = 190, 
        apRadius = 0, 
        apForce = 0, 
        heRadius = 0, 
        heForce = 0, 
        frForce = 0, 
        frForceMin = 0, 
        frRadius = 0, 
        avScale = 0.001, 
        reloadTime = 1, 
        sticky = false, 
        explOnContact = false, 
        lifeTime = 6, 
        carryMax = 3, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    Cache = {
        class = "Crate", 
        type = "bomb", 
        protoBolt = v6("ProtoBomb"), 
        range = 1, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 10, 
        apForce = 200, 
        heRadius = 10, 
        heForce = 200, 
        frRadius = 10, 
        frForce = 200, 
        avScale = 85
    }, 
    Shell_HowSm_AP = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 1.2, 
        tracerFadeRate = 0.8, 
        tracerWidthIncr = -0.6363636363636364, 
        range = 1000, 
        loArcSpeed = 840, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 8.2, 
        apForce = 235, 
        heRadius = 7, 
        heForce = 200, 
        frForce = 240, 
        frForceMin = 30, 
        frRadius = 32, 
        frRadiusMin = 15, 
        avScale = 60, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                range = 1100, 
                apRadius = 9.2, 
                apForce = 252, 
                heRadius = 7.8, 
                heForce = 224, 
                frForce = 268.8, 
                frForceMin = 33.6, 
                frRadius = 35.8, 
                frRadiusMin = 16.8, 
                avScale = 72
            }, 
            {
                name = "FastReload", 
                range = 960, 
                loArcSpeed = 740, 
                apRadius = 7.1, 
                apForce = 196, 
                heRadius = 6.1, 
                heForce = 174, 
                frForce = 208.8, 
                frForceMin = 26.1, 
                frRadius = 27.8, 
                frRadiusMin = 13.1, 
                reloadTime = 3.5, 
                avScale = 50
            }, 
            {
                name = "LongRange", 
                range = 1500, 
                loArcSpeed = 932, 
                apRadius = 7.1, 
                apForce = 196, 
                heRadius = 6.1, 
                heForce = 174, 
                frForce = 208.8, 
                frForceMin = 26.1, 
                frRadius = 27.8, 
                frRadiusMin = 13.1, 
                avScale = 50
            }
        }
    }, 
    Shell_BaseSentry = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 950, 
        loArcSpeed = 1000, 
        loArcGravity = 30, 
        hiArcSpeed = 880, 
        hiArcGravity = 800, 
        apRadius = 8.2, 
        apForce = 225, 
        heRadius = 7, 
        heForce = 200, 
        frForce = 240, 
        frForceMin = 30, 
        frRadius = 32, 
        frRadiusMin = 15, 
        avScale = 60, 
        reloadTime = 4, 
        upgradeList = {}, 
        upgrades = {
            {
                reloadTime = 2.2, 
                tracerWidth = 0.8, 
                tracerFadeRate = 0.8, 
                tracerWidthIncr = -0.7272727272727273, 
                name = "Premium", 
                range = 1150, 
                apForce = 240, 
                heForce = 350, 
                loArcSpeed = 1000, 
                frRadiusMin = 30, 
                avScale = 72
            }
        }
    }, 
    Shell_HowSm_HE = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 1.2, 
        tracerFadeRate = 0.8, 
        tracerWidthIncr = -0.6363636363636364, 
        range = 960, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 480, 
        hiArcGravity = 400, 
        apRadius = 6.3, 
        apForce = 180, 
        heRadius = 10, 
        heForce = 200, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 32, 
        avScale = 60, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 7.1, 
                apForce = 202, 
                heRadius = 11.2, 
                heForce = 224, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 35.8, 
                avScale = 72
            }, 
            {
                name = "FastReload", 
                range = 960, 
                apRadius = 5.5, 
                apForce = 157, 
                heRadius = 8.7, 
                heForce = 174, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 27.8, 
                reloadTime = 3.5, 
                avScale = 50
            }, 
            {
                name = "LongRange", 
                range = 1440, 
                apRadius = 5.5, 
                apForce = 157, 
                heRadius = 8.7, 
                heForce = 174, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 27.8, 
                avScale = 50
            }
        }
    }, 
    Shell_KV2 = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("kv2"), 
        tracerWidth = 3, 
        tracerFadeRate = 0.9, 
        range = 720, 
        loArcSpeed = 300, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        spread = 0.08748866352592401, 
        apRadius = 5, 
        apForce = 200, 
        heRadius = 5, 
        heForce = 100, 
        shotCount = 1, 
        frForce = 200, 
        frForceMin = 15, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 60, 
        reloadTime = 2.7, 
        upgradeList = {}, 
        afterShotFunc = function(v10) --[[ Line: 516 ]] --[[ Name: afterShotFunc ]]
            local v11 = math.random();
            local v12 = math.random();
            v10.range = 700 + 1100 * math.random();
            v10.loArcSpeed = 100 + 400 * math.random();
            v10.loArcGravity = 1 + 5 * math.random();
            v10.shotCount = 1 + 10 * math.random();
            v10.apRadius = 2 + 7 * v11;
            v10.apForce = 70 + 200 * v12;
            v10.heRadius = 2 + 14 * math.random();
            v10.heForce = 40 + 200 * math.random();
            v10.frForce = 80 + 200 * math.random();
            v10.frForceMin = 15 + 40 * math.random();
            v10.reloadTime = 0.1 + 2 * math.random();
            v10.avScale = 35 + 55 * (v12 * v11);
        end, 
        upgrades = {}
    }, 
    Shell_KV1 = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 720, 
        loArcSpeed = 300, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5, 
        apForce = 200, 
        heRadius = 5, 
        heForce = 100, 
        frForce = 200, 
        frForceMin = 15, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 60, 
        reloadTime = 4, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    Shell_HowQF_HE = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 1100, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 720, 
        hiArcGravity = 400, 
        apRadius = 8.4, 
        apForce = 180, 
        heRadius = 13, 
        heForce = 250, 
        frForce = 250, 
        frForceMin = 37, 
        frRadius = 40, 
        avScale = 60, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 9.4, 
                apForce = 202, 
                heRadius = 14.6, 
                heForce = 280, 
                frForce = 280, 
                frForceMin = 41.4, 
                frRadius = 44.8, 
                avScale = 72
            }, 
            {
                name = "FastReload", 
                range = 1100, 
                apRadius = 7.3, 
                apForce = 157, 
                heRadius = 11.3, 
                heForce = 218, 
                frForce = 217.5, 
                frForceMin = 32.2, 
                frRadius = 34.8, 
                reloadTime = 3.5, 
                avScale = 50
            }, 
            {
                name = "LongRange", 
                range = 1650, 
                apRadius = 7.3, 
                apForce = 157, 
                heRadius = 11.3, 
                heForce = 218, 
                frForce = 217.5, 
                frForceMin = 32.2, 
                frRadius = 34.8, 
                avScale = 50
            }
        }
    }, 
    Missile_Truck = {
        class = "Missile", 
        type = "missile", 
        protoBolt = v6("ProtoRpg"), 
        range = 900, 
        loArcSpeed = 500, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 200, 
        heRadius = 8, 
        heForce = 100, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 28, 
        frRadiusMin = 12, 
        maxTrackAngle = 0.017453292519943295, 
        avScale = 40, 
        reloadTime = 4, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                loArcSpeed = 500, 
                range = 1100, 
                apRadius = 7.4, 
                apForce = 200, 
                heRadius = 11.2, 
                heForce = 140, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 31.4, 
                frRadiusMin = 13.4, 
                avScale = 45
            }, 
            {
                name = "LongRange", 
                range = 1250, 
                loArcSpeed = 520, 
                apRadius = 4.6, 
                apForce = 170, 
                heRadius = 7, 
                heForce = 87, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 24.4, 
                frRadiusMin = 10.4, 
                avScale = 33
            }
        }
    }, 
    Shell_FV101_AP = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 780, 
        loArcSpeed = 800, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 210, 
        heRadius = 7, 
        heForce = 180, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 30, 
        reloadTime = 4.5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 5.9, 
                apForce = 235, 
                heRadius = 7.8, 
                heForce = 202, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                frRadiusMin = 13.4, 
                avScale = 36
            }, 
            {
                name = "FastReload", 
                range = 780, 
                loArcSpeed = 800, 
                apRadius = 4.6, 
                apForce = 183, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                reloadTime = 3.15, 
                avScale = 25
            }, 
            {
                name = "LongRange", 
                range = 1170, 
                loArcSpeed = 1040, 
                apRadius = 4.6, 
                apForce = 183, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                avScale = 25
            }
        }
    }, 
    BTR_Direct = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 650, 
        loArcSpeed = 640, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 150, 
        heRadius = 8, 
        heForce = 100, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 30, 
        spread = 0.024439473585260857, 
        reloadTime = 3, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                range = 720, 
                loArcSpeed = 640, 
                apRadius = 5.9, 
                apForce = 170, 
                heRadius = 9, 
                heForce = 112, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                frRadiusMin = 13.4, 
                avScale = 36
            }
        }
    }, 
    Shell_V150_AP = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 650, 
        loArcSpeed = 700, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 150, 
        heRadius = 8, 
        heForce = 100, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 30, 
        reloadTime = 2.8, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                range = 720, 
                loArcSpeed = 940, 
                apRadius = 5.9, 
                apForce = 170, 
                heRadius = 9, 
                heForce = 112, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                frRadiusMin = 13.4, 
                avScale = 36
            }, 
            {
                name = "FastReload", 
                range = 580, 
                loArcSpeed = 640, 
                apRadius = 4.6, 
                apForce = 131, 
                heRadius = 7, 
                heForce = 87, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                reloadTime = 2, 
                avScale = 25
            }, 
            {
                name = "LongRange", 
                range = 1100, 
                loArcSpeed = 832, 
                apRadius = 4.6, 
                apForce = 131, 
                heRadius = 7, 
                heForce = 87, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                avScale = 25
            }
        }
    }, 
    Shell_V150_HE = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 580, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 480, 
        hiArcGravity = 400, 
        apRadius = 5.3, 
        apForce = 126, 
        heRadius = 7, 
        heForce = 90, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 35, 
        avScale = 33, 
        reloadTime = 3, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 5.9, 
                apForce = 140, 
                heRadius = 7.8, 
                heForce = 120, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                avScale = 40
            }, 
            {
                name = "FastReload", 
                range = 480, 
                apRadius = 4.6, 
                apForce = 98, 
                heRadius = 6.1, 
                heForce = 60, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                reloadTime = 2.5, 
                avScale = 27
            }, 
            {
                name = "LongRange", 
                range = 720, 
                apRadius = 4.6, 
                apForce = 98, 
                heRadius = 6.1, 
                heForce = 60, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                avScale = 27
            }
        }
    }, 
    Shell_VecM1_AP = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 650, 
        loArcSpeed = 720, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 210, 
        heRadius = 8, 
        heForce = 120, 
        frForce = 160, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 33, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 5.9, 
                apForce = 235, 
                heRadius = 9, 
                heForce = 134, 
                frForce = 179.2, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                frRadiusMin = 13.4, 
                avScale = 40
            }, 
            {
                name = "FastReload", 
                range = 650, 
                loArcSpeed = 720, 
                apRadius = 4.6, 
                apForce = 183, 
                heRadius = 7, 
                heForce = 104, 
                frForce = 139.2, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                reloadTime = 3.5, 
                avScale = 27
            }, 
            {
                name = "LongRange", 
                range = 1100, 
                loArcSpeed = 936, 
                apRadius = 4.6, 
                apForce = 183, 
                heRadius = 7, 
                heForce = 104, 
                frForce = 139.2, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                avScale = 27
            }
        }
    }, 
    Shell_VecM1_HE = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 600, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 540, 
        hiArcGravity = 400, 
        apRadius = 5.3, 
        apForce = 135, 
        heRadius = 8, 
        heForce = 200, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 35, 
        avScale = 37, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 5.9, 
                apForce = 151, 
                heRadius = 9, 
                heForce = 224, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                avScale = 44
            }, 
            {
                name = "FastReload", 
                range = 600, 
                apRadius = 4.6, 
                apForce = 117, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                reloadTime = 3.5, 
                avScale = 31
            }, 
            {
                name = "LongRange", 
                range = 900, 
                apRadius = 4.6, 
                apForce = 117, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                avScale = 31
            }
        }
    }, 
    Shell_Mortar_HE = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 420, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 480, 
        hiArcGravity = 300, 
        apRadius = 5.3, 
        apForce = 105, 
        heRadius = 7, 
        heForce = 140, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 35, 
        avScale = 33, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 5.9, 
                apForce = 118, 
                heRadius = 7.8, 
                heForce = 157, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                avScale = 40
            }, 
            {
                name = "FastReload", 
                range = 420, 
                apRadius = 4.6, 
                apForce = 91, 
                heRadius = 6.1, 
                heForce = 122, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                reloadTime = 3.5, 
                avScale = 27
            }, 
            {
                name = "LongRange", 
                range = 630, 
                apRadius = 4.6, 
                apForce = 91, 
                heRadius = 6.1, 
                heForce = 122, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                avScale = 27
            }
        }
    }, 
    Shell_M48A5 = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 820, 
        loArcSpeed = 640, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 255, 
        heRadius = 7, 
        heForce = 180, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 37, 
        frRadiusMin = 13, 
        avScale = 40, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                range = 950, 
                apRadius = 5.9, 
                apForce = 286, 
                heRadius = 7.8, 
                heForce = 202, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 41.4, 
                frRadiusMin = 14.6, 
                avScale = 48
            }, 
            {
                name = "FastReload", 
                range = 720, 
                loArcSpeed = 640, 
                apRadius = 4.6, 
                apForce = 222, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                reloadTime = 3.5, 
                avScale = 33
            }, 
            {
                name = "LongRange", 
                range = 1080, 
                loArcSpeed = 832, 
                apRadius = 4.6, 
                apForce = 222, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                avScale = 33
            }
        }
    }, 
    Shell_Leopard = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 780, 
        loArcSpeed = 800, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 6.3, 
        apForce = 255, 
        heRadius = 8, 
        heForce = 200, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 40, 
        reloadTime = 4.5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 7.1, 
                apForce = 286, 
                heRadius = 9, 
                heForce = 224, 
                frForce = 246.4, 
                frForceMin = 35.8, 
                frRadius = 44.8, 
                frRadiusMin = 16.8, 
                avScale = 48
            }, 
            {
                name = "FastReload", 
                range = 780, 
                loArcSpeed = 800, 
                apRadius = 5.5, 
                apForce = 222, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                reloadTime = 3.15, 
                avScale = 33
            }, 
            {
                name = "LongRange", 
                range = 1170, 
                loArcSpeed = 1040, 
                apRadius = 5.5, 
                apForce = 222, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                avScale = 33
            }
        }
    }, 
    Shell_Elephant = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        tracerWidthIncr = -0.7272727272727273, 
        range = 1450, 
        loArcSpeed = 600, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 8.3, 
        apForce = 355, 
        heRadius = 8.5, 
        heForce = 230, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 60, 
        reloadTime = 8, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    Shell_Karl = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("karl"), 
        range = 1200, 
        loArcSpeed = 230, 
        loArcGravity = 20, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        hitRadius = 5, 
        spread = 0.10510423526567647, 
        magGroup = "A", 
        magMax = 3, 
        magReloadTime = 25, 
        shotCount = 4, 
        apRadius = 20, 
        apForce = 220, 
        heRadius = 40, 
        heForce = 180, 
        frForce = 240, 
        frForceMin = 30, 
        frRadius = 305, 
        frRadiusMin = 102, 
        tracerWidth = 8, 
        tracerWidthIncr = -1.5454545454545454, 
        tracerFadeRate = 0.8, 
        avScale = 140, 
        reloadTime = 2, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    Shell_Sturmtiger = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoXLShell"), 
        range = 1200, 
        loArcSpeed = 330, 
        loArcGravity = 20, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 22, 
        apForce = 220, 
        heRadius = 40, 
        heForce = 250, 
        frForce = 240, 
        frForceMin = 30, 
        frRadius = 305, 
        frRadiusMin = 102, 
        tracerWidth = 8, 
        tracerWidthIncr = -2.4545454545454546, 
        tracerFadeRate = 0.9, 
        avScale = 100, 
        reloadTime = 18, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "FastReload", 
                tracerWidth = 6, 
                tracerWidthIncr = -1.8181818181818181, 
                tracerFadeRate = 0.9, 
                loArcSpeed = 530, 
                range = 900, 
                frForce = 200, 
                apForce = 190, 
                heForce = 150, 
                reloadTime = 12, 
                avScale = 70
            }
        }
    }, 
    Shell_Panther = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 880, 
        loArcSpeed = 750, 
        loArcGravity = 20, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 220, 
        heRadius = 7, 
        heForce = 180, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 50, 
        reloadTime = 4.5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                loArcSpeed = 850, 
                range = 900, 
                apRadius = 5.9, 
                apForce = 235, 
                heRadius = 7.8, 
                heForce = 202, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                frRadiusMin = 13.4, 
                avScale = 60
            }, 
            {
                name = "FastReload", 
                range = 820, 
                loArcSpeed = 900, 
                apRadius = 4.6, 
                apForce = 200, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                reloadTime = 3.15, 
                avScale = 45
            }, 
            {
                name = "LongRange", 
                range = 1170, 
                loArcSpeed = 1000, 
                apRadius = 4.6, 
                apForce = 200, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                avScale = 45
            }
        }
    }, 
    Shell_Tiger = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 1.3, 
        tracerFadeRate = 0.7, 
        range = 980, 
        loArcSpeed = 970, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 235, 
        heRadius = 7, 
        heForce = 160, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 50, 
        reloadTime = 4.5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                range = 1100, 
                apRadius = 5.9, 
                apForce = 255, 
                heRadius = 7.8, 
                heForce = 180, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                frRadiusMin = 13.4, 
                avScale = 60
            }, 
            {
                name = "FastReload", 
                range = 780, 
                loArcSpeed = 990, 
                apRadius = 4.6, 
                apForce = 210, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                reloadTime = 2.5, 
                avScale = 45, 
                spread = 0.020947013909659987
            }, 
            {
                name = "LongRange", 
                range = 1170, 
                loArcSpeed = 1040, 
                apRadius = 4.6, 
                apForce = 210, 
                heRadius = 6.1, 
                heForce = 157, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                frRadiusMin = 10.4, 
                avScale = 45
            }
        }
    }, 
    Shell_T34 = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 874, 
        loArcSpeed = 720, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 6.3, 
        apForce = 165, 
        heRadius = 8, 
        heForce = 200, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 35, 
        reloadTime = 4.5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                loArcSpeed = 750, 
                apRadius = 7.1, 
                apForce = 187, 
                heRadius = 9, 
                heForce = 234, 
                frForce = 246.4, 
                frForceMin = 35.8, 
                frRadius = 44.8, 
                frRadiusMin = 16.8, 
                avScale = 48
            }, 
            {
                name = "FastReload", 
                range = 744, 
                loArcSpeed = 720, 
                apRadius = 5.5, 
                apForce = 144, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                reloadTime = 3.15, 
                avScale = 33
            }, 
            {
                name = "LongRange", 
                range = 1116, 
                loArcSpeed = 936, 
                apRadius = 5.5, 
                apForce = 144, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                avScale = 33
            }
        }
    }, 
    Shell_GrantMain = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 1, 
        tracerFadeRate = 0.7, 
        range = 580, 
        loArcSpeed = 700, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        spread = 0.017455064928217585, 
        apRadius = 10, 
        apForce = 100, 
        heRadius = 7, 
        heForce = 100, 
        frForce = 120, 
        frForceMin = 30, 
        frRadius = 20, 
        frRadiusMin = 12, 
        avScale = 32, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    Shell_GrantHull = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.8, 
        tracerWidthIncr = -0.7272727272727273, 
        range = 1000, 
        loArcSpeed = 420, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 10, 
        apForce = 350, 
        heRadius = 9, 
        heForce = 165, 
        spread = 0.017455064928217585, 
        frForce = 170, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 55, 
        reloadTime = 12, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    Shell_GrantHullArc = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.8, 
        tracerWidthIncr = -0.7272727272727273, 
        range = 800, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 800, 
        hiArcGravity = 800, 
        apRadius = 10, 
        apForce = 350, 
        heRadius = 10, 
        heForce = 175, 
        spread = 0.02618592156918693, 
        frForce = 170, 
        frForceMin = 30, 
        frRadius = 35, 
        frRadiusMin = 12, 
        avScale = 55, 
        reloadTime = 12, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    RocketArtilleryDirect = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 900, 
        loArcSpeed = 1000, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 126, 
        heRadius = 7, 
        heForce = 90, 
        shotCount = 5, 
        spread = 0.08748866352592401, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 35, 
        avScale = 33, 
        reloadTime = 8, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 5.9, 
                apForce = 140, 
                heRadius = 7.8, 
                heForce = 120, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                avScale = 40
            }, 
            {
                reloadTime = 6.5, 
                shotCount = 5, 
                spread = 0.1227845609029046, 
                name = "FastReload", 
                range = 700, 
                apRadius = 4.6, 
                apForce = 98, 
                heRadius = 6.1, 
                heForce = 60, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                avScale = 27
            }, 
            {
                shotCount = 5, 
                spread = 0.06641992671492261, 
                name = "LongRange", 
                range = 900, 
                apRadius = 4.6, 
                apForce = 98, 
                heRadius = 6.1, 
                heForce = 60, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                avScale = 27
            }
        }
    }, 
    RocketArtillery = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 750, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 480, 
        hiArcGravity = 400, 
        apRadius = 5.3, 
        apForce = 126, 
        heRadius = 7, 
        heForce = 90, 
        shotCount = 5, 
        spread = 0.08748866352592401, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 35, 
        avScale = 33, 
        reloadTime = 9, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 5.9, 
                apForce = 140, 
                heRadius = 7.8, 
                heForce = 120, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 39.2, 
                avScale = 40
            }, 
            {
                reloadTime = 7, 
                shotCount = 5, 
                spread = 0.1227845609029046, 
                name = "FastReload", 
                range = 700, 
                apRadius = 4.6, 
                apForce = 98, 
                heRadius = 6.1, 
                heForce = 60, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                avScale = 27
            }, 
            {
                shotCount = 5, 
                spread = 0.06641992671492261, 
                name = "LongRange", 
                range = 900, 
                apRadius = 4.6, 
                apForce = 98, 
                heRadius = 6.1, 
                heForce = 60, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 30.5, 
                avScale = 27
            }
        }
    }, 
    Shell_AMX = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 850, 
        loArcSpeed = 820, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        shotCount = 3, 
        apRadius = 3, 
        apForce = 385, 
        heRadius = 8, 
        heForce = 100, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 40, 
        spread = 0.06992681194351041, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 3, 
                apForce = 450, 
                heRadius = 9, 
                heForce = 100, 
                frForce = 246.4, 
                frForceMin = 35.8, 
                frRadius = 44.8, 
                frRadiusMin = 16.8, 
                avScale = 48
            }, 
            {
                name = "FastReload", 
                range = 744, 
                shotCount = 2.7, 
                loArcSpeed = 850, 
                apRadius = 2, 
                apForce = 350, 
                heRadius = 7, 
                heForce = 80, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                reloadTime = 3, 
                avScale = 33, 
                spread = 0.08748866352592401
            }, 
            {
                name = "LongRange", 
                range = 1116, 
                loArcSpeed = 1110, 
                apRadius = 3, 
                apForce = 270, 
                heRadius = 7, 
                heForce = 70, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                avScale = 33, 
                spread = 0.05590867980926056
            }
        }
    }, 
    Shell_Sherman = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.7, 
        range = 744, 
        loArcSpeed = 820, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 6.3, 
        apForce = 165, 
        heRadius = 8, 
        heForce = 200, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 40, 
        reloadTime = 4, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 7.1, 
                apForce = 185, 
                heRadius = 9, 
                heForce = 224, 
                frForce = 246.4, 
                frForceMin = 35.8, 
                frRadius = 44.8, 
                frRadiusMin = 16.8, 
                avScale = 48
            }, 
            {
                name = "FastReload", 
                range = 744, 
                loArcSpeed = 720, 
                apRadius = 5.5, 
                apForce = 144, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                reloadTime = 3.15, 
                avScale = 33
            }, 
            {
                name = "LongRange", 
                range = 1116, 
                loArcSpeed = 936, 
                apRadius = 5.5, 
                apForce = 144, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                avScale = 33
            }
        }
    }, 
    Shell_ISU = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 1.2, 
        tracerFadeRate = 0.8, 
        tracerWidthIncr = -0.2727272727272727, 
        range = 874, 
        loArcSpeed = 900, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 7.3, 
        apForce = 210, 
        heRadius = 8, 
        heForce = 200, 
        spread = 0.03492076949174773, 
        magGroup = "A", 
        magMax = 5, 
        magReloadTime = 15, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 40, 
        reloadTime = 1, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                loArcSpeed = 1250, 
                apRadius = 8.1, 
                apForce = 240, 
                heRadius = 9, 
                heForce = 234, 
                frForce = 246.4, 
                frForceMin = 35.8, 
                frRadius = 44.8, 
                frRadiusMin = 16.8, 
                avScale = 48
            }
        }
    }, 
    Shell_SU_Direct = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 1.2, 
        tracerFadeRate = 0.95, 
        tracerWidthIncr = -0.2727272727272727, 
        range = 874, 
        loArcSpeed = 900, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 7.3, 
        apForce = 210, 
        heRadius = 8, 
        heForce = 200, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 40, 
        reloadTime = 5.5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                loArcSpeed = 1250, 
                apRadius = 8.1, 
                apForce = 240, 
                heRadius = 9, 
                heForce = 234, 
                frForce = 246.4, 
                frForceMin = 35.8, 
                frRadius = 44.8, 
                frRadiusMin = 16.8, 
                avScale = 48
            }, 
            {
                name = "FastReload", 
                range = 744, 
                loArcSpeed = 1120, 
                apRadius = 6.5, 
                apForce = 175, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                reloadTime = 4, 
                avScale = 34
            }, 
            {
                name = "LongRange", 
                range = 1416, 
                loArcSpeed = 936, 
                apRadius = 6.5, 
                apForce = 200, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                avScale = 37
            }
        }
    }, 
    Shell_SUIndirect = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 1.2, 
        tracerFadeRate = 0.95, 
        tracerWidthIncr = -0.2727272727272727, 
        range = 874, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 800, 
        hiArcGravity = 800, 
        apRadius = 6.3, 
        apForce = 205, 
        heRadius = 8, 
        heForce = 200, 
        frForce = 220, 
        frForceMin = 32, 
        frRadius = 40, 
        frRadiusMin = 15, 
        avScale = 60, 
        reloadTime = 5.5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 7.1, 
                apForce = 235, 
                heRadius = 12, 
                heForce = 234, 
                frForce = 246.4, 
                frForceMin = 35.8, 
                frRadius = 44.8, 
                frRadiusMin = 16.8, 
                avScale = 48
            }, 
            {
                name = "FastReload", 
                range = 744, 
                apRadius = 7, 
                apForce = 144, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                reloadTime = 4, 
                avScale = 34
            }, 
            {
                name = "LongRange", 
                range = 1116, 
                apRadius = 6, 
                apForce = 174, 
                heRadius = 7, 
                heForce = 174, 
                frForce = 191.4, 
                frForceMin = 27.8, 
                frRadius = 34.8, 
                frRadiusMin = 13.1, 
                avScale = 37
            }
        }
    }, 
    Shell_M109 = {
        class = "Shell", 
        type = "tracer", 
        protoBolt = v6("ProtoShell"), 
        tracerWidth = 0.8, 
        tracerFadeRate = 0.8, 
        tracerWidthIncr = -0.7272727272727273, 
        range = 1200, 
        loArcSpeed = 1, 
        loArcGravity = 1, 
        hiArcSpeed = 800, 
        hiArcGravity = 800, 
        apRadius = 8.4, 
        apForce = 255, 
        heRadius = 10, 
        heForce = 200, 
        frForce = 200, 
        frForceMin = 30, 
        frRadius = 32, 
        avScale = 60, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 9.4, 
                apForce = 286, 
                heRadius = 11.2, 
                heForce = 224, 
                frForce = 224, 
                frForceMin = 33.6, 
                frRadius = 35.8, 
                avScale = 72
            }, 
            {
                name = "FastReload", 
                range = 1200, 
                apRadius = 7.3, 
                apForce = 222, 
                heRadius = 8.7, 
                heForce = 174, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 27.8, 
                reloadTime = 3.5, 
                avScale = 50
            }, 
            {
                name = "LongRange", 
                range = 1800, 
                apRadius = 7.3, 
                apForce = 222, 
                heRadius = 8.7, 
                heForce = 174, 
                frForce = 174, 
                frForceMin = 26.1, 
                frRadius = 27.8, 
                avScale = 50
            }
        }
    }, 
    Missile_Huey_AP = {
        class = "Missile", 
        type = "missile", 
        protoBolt = v6("ProtoRpg"), 
        range = 720, 
        loArcSpeed = 560, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 200, 
        heRadius = 8, 
        heForce = 100, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 28, 
        frRadiusMin = 12, 
        maxTrackAngle = 0.017453292519943295, 
        avScale = 40, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 7.4, 
                apForce = 202, 
                heRadius = 11.2, 
                heForce = 140, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 31.4, 
                frRadiusMin = 13.4, 
                avScale = 45
            }, 
            {
                name = "LongRange", 
                range = 1080, 
                loArcSpeed = 1120, 
                apRadius = 4.6, 
                apForce = 157, 
                heRadius = 7, 
                heForce = 87, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 24.4, 
                frRadiusMin = 10.4, 
                avScale = 33
            }
        }
    }, 
    Heatray = {
        class = "Missile", 
        type = "missile", 
        protoBolt = v6("ProtoHeatray"), 
        range = 1000, 
        loArcSpeed = 860, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        name = "Premium", 
        apRadius = 7.4, 
        apForce = 202, 
        heRadius = 11.2, 
        heForce = 180, 
        frForce = 156.8, 
        frForceMin = 33.6, 
        frRadius = 31.4, 
        frRadiusMin = 13.4, 
        avScale = 45, 
        maxTrackAngle = 0.017453292519943295, 
        reloadTime = 1.5, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    Missile_Truck_G = {
        class = "Missile", 
        type = "missile", 
        protoBolt = v6("ProtoRpg"), 
        range = 800, 
        loArcSpeed = 160, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 180, 
        heRadius = 8, 
        heForce = 100, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 28, 
        frRadiusMin = 12, 
        guided = true, 
        maxTrackAngle = 0.008726646259971648, 
        avScale = 40, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 7.4, 
                apForce = 202, 
                heRadius = 11.2, 
                heForce = 140, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 31.4, 
                frRadiusMin = 13.4, 
                avScale = 45
            }, 
            {
                name = "LongRange", 
                range = 1080, 
                loArcSpeed = 300, 
                apRadius = 4.6, 
                apForce = 157, 
                heRadius = 7, 
                heForce = 87, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 24.4, 
                frRadiusMin = 10.4, 
                avScale = 33
            }
        }
    }, 
    Missile_Truck_T = {
        class = "Missile", 
        type = "missile", 
        protoBolt = v6("ProtoRpg"), 
        range = 800, 
        loArcSpeed = 160, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 5.3, 
        apForce = 180, 
        heRadius = 8, 
        heForce = 100, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 28, 
        frRadiusMin = 12, 
        tracking = true, 
        maxTrackAngle = 0.003141592653589793, 
        maxTrackAngleHeli = 0.0017453292519943296, 
        maxTrackAngleGuided = 0.008726646259971648, 
        avScale = 40, 
        reloadTime = 5, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 7.4, 
                apForce = 202, 
                heRadius = 11.2, 
                heForce = 140, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 31.4, 
                frRadiusMin = 13.4, 
                avScale = 45
            }, 
            {
                name = "LongRange", 
                range = 1080, 
                loArcSpeed = 300, 
                apRadius = 4.6, 
                apForce = 157, 
                heRadius = 7, 
                heForce = 87, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 24.4, 
                frRadiusMin = 10.4, 
                avScale = 33
            }
        }
    }, 
    Damaged50Cal = {
        class = "50Cal", 
        type = "bullet", 
        protoBolt = v6("ProtoBullet"), 
        range = 650, 
        loArcSpeed = 980, 
        loArcGravity = 40, 
        hiArcSpeed = 800, 
        hiArcGravity = 50, 
        spread = 0.06992681194351041, 
        apRadius = 0, 
        apForce = 80, 
        heRadius = 0, 
        heForce = 0, 
        frRadius = 0, 
        frForce = 40, 
        avScale = 30, 
        reloadTime = 0.18, 
        upgradeList = {}, 
        upgrades = {}
    }, 
    ["35mm_Huey"] = {
        class = "25mm", 
        type = "slug", 
        protoBolt = v6("ProtoSlug"), 
        range = 900, 
        loArcSpeed = 1600, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 0, 
        apForce = 70, 
        heRadius = 0, 
        heForce = 70, 
        frForce = 20, 
        frForceMin = 30, 
        frRadius = 37, 
        frRadiusMin = 13, 
        hitRadius = 2, 
        hitPartMax = 1, 
        avScale = 15, 
        reloadTime = 0.24, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 0, 
                apForce = 90, 
                heRadius = 0, 
                heForce = 78, 
                frForce = 22.4, 
                frForceMin = 33.6, 
                frRadius = 41.4, 
                frRadiusMin = 14.6, 
                avScale = 20
            }, 
            {
                name = "LongRange", 
                range = 1260, 
                loArcSpeed = 2080, 
                apRadius = 0, 
                apForce = 70, 
                heRadius = 0, 
                heForce = 61, 
                frForce = 17.4, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                avScale = 12
            }
        }
    }, 
    ["25mm_Huey"] = {
        class = "25mm", 
        type = "slug", 
        protoBolt = v6("ProtoSlug"), 
        range = 900, 
        loArcSpeed = 1600, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 0, 
        apForce = 35, 
        heRadius = 0, 
        heForce = 70, 
        frForce = 20, 
        frForceMin = 30, 
        frRadius = 37, 
        frRadiusMin = 13, 
        hitRadius = 2, 
        hitPartMax = 1, 
        avScale = 13, 
        reloadTime = 0.33, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 0, 
                apForce = 39, 
                heRadius = 0, 
                heForce = 78, 
                frForce = 22.4, 
                frForceMin = 33.6, 
                frRadius = 41.4, 
                frRadiusMin = 14.6, 
                avScale = 16
            }, 
            {
                name = "LongRange", 
                range = 1260, 
                loArcSpeed = 2080, 
                apRadius = 0, 
                apForce = 30, 
                heRadius = 0, 
                heForce = 61, 
                frForce = 17.4, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                avScale = 11
            }
        }
    }, 
    ["25mm_V150"] = {
        class = "25mm", 
        type = "slug", 
        protoBolt = v6("ProtoSlug"), 
        range = 900, 
        loArcSpeed = 1600, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 0, 
        apForce = 55, 
        heRadius = 0, 
        heForce = 70, 
        frForce = 30, 
        frForceMin = 30, 
        frRadius = 37, 
        frRadiusMin = 13, 
        hitRadius = 6, 
        hitPartMax = 2, 
        avScale = 13, 
        reloadTime = 0.33, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 0, 
                apForce = 62, 
                heRadius = 0, 
                heForce = 78, 
                frForce = 33.6, 
                frForceMin = 33.6, 
                frRadius = 41.4, 
                frRadiusMin = 14.6, 
                avScale = 16
            }, 
            {
                name = "LongRange", 
                range = 1260, 
                loArcSpeed = 2080, 
                apRadius = 0, 
                apForce = 48, 
                heRadius = 0, 
                heForce = 61, 
                frForce = 26.1, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                avScale = 11
            }
        }
    }, 
    ["25mm_VecM1"] = {
        class = "25mm", 
        type = "slug", 
        protoBolt = v6("ProtoSlug"), 
        range = 1100, 
        loArcSpeed = 1760, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 0, 
        apForce = 62, 
        heRadius = 0, 
        heForce = 70, 
        frForce = 40, 
        frForceMin = 30, 
        frRadius = 37, 
        frRadiusMin = 13, 
        hitRadius = 8, 
        hitPartMax = 3, 
        avScale = 13, 
        aScale = 15, 
        reloadTime = 0.33, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 0, 
                apForce = 69, 
                heRadius = 0, 
                heForce = 78, 
                frForce = 44.8, 
                frForceMin = 33.6, 
                frRadius = 41.4, 
                frRadiusMin = 14.6, 
                avScale = 16
            }, 
            {
                name = "LongRange", 
                range = 1540, 
                loArcSpeed = 2288, 
                apRadius = 0, 
                apForce = 54, 
                heRadius = 0, 
                heForce = 61, 
                frForce = 34.8, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                avScale = 11
            }
        }
    }, 
    ["50CalSlow"] = {
        class = "50Cal", 
        type = "bullet", 
        protoBolt = v6("ProtoBullet"), 
        range = 750, 
        loArcSpeed = 1200, 
        loArcGravity = 40, 
        hiArcSpeed = 800, 
        hiArcGravity = 50, 
        spread = 0.03492076949174773, 
        apRadius = 0, 
        apForce = 80, 
        heRadius = 0, 
        heForce = 0, 
        frRadius = 0, 
        frForce = 40, 
        avScale = 30, 
        reloadTime = 0, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Auto", 
                reloadTime = 0.25, 
                avScale = 40
            }
        }
    }, 
    ["25mm_BTR80A"] = {
        class = "25mm", 
        type = "slug", 
        protoBolt = v6("ProtoSlug"), 
        range = 999, 
        loArcSpeed = 1920, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        spread = 0.03492076949174773, 
        apRadius = 0, 
        apForce = 95, 
        heRadius = 0, 
        heForce = 95, 
        frForce = 40, 
        frForceMin = 30, 
        frRadius = 37, 
        frRadiusMin = 13, 
        hitRadius = 3, 
        hitPartMax = 1, 
        avScale = 18, 
        reloadTime = 0.22, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 0, 
                apForce = 99, 
                heRadius = 0, 
                heForce = 99, 
                frForce = 44.8, 
                frForceMin = 33.6, 
                frRadius = 41.4, 
                frRadiusMin = 14.6, 
                avScale = 26, 
                hitPartMax = 2
            }, 
            {
                name = "LongRange", 
                range = 1540, 
                loArcSpeed = 2496, 
                apRadius = 0, 
                apForce = 90, 
                heRadius = 0, 
                heForce = 90, 
                frForce = 34.8, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                hitPartMax = 1, 
                avScale = 11, 
                spread = 0.0384161249828123
            }
        }
    }, 
    ["25mm_Bofors"] = {
        class = "25mm", 
        type = "slug", 
        protoBolt = v6("ProtoSlug"), 
        range = 1100, 
        loArcSpeed = 1540, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 0, 
        apForce = 90, 
        heRadius = 0, 
        heForce = 130, 
        frForce = 40, 
        frForceMin = 30, 
        frRadius = 37, 
        frRadiusMin = 13, 
        hitRadius = 8, 
        hitPartMax = 3, 
        avScale = 20, 
        reloadTime = 0.28, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                apRadius = 0, 
                apForce = 100, 
                heRadius = 0, 
                heForce = 140, 
                frForce = 44.8, 
                frForceMin = 33.6, 
                frRadius = 41.4, 
                frRadiusMin = 14.6, 
                avScale = 25
            }, 
            {
                name = "LongRange", 
                range = 1680, 
                loArcSpeed = 3432, 
                apRadius = 0, 
                apForce = 91, 
                heRadius = 0, 
                heForce = 91, 
                frForce = 34.8, 
                frForceMin = 26.1, 
                frRadius = 32.2, 
                frRadiusMin = 11.3, 
                hitPartMax = 2, 
                avScale = 18
            }
        }
    }, 
    Rocket = {
        class = "Rocket", 
        type = "missile", 
        protoBolt = v6("ProtoRpg"), 
        range = 540, 
        loArcSpeed = 640, 
        loArcGravity = 30, 
        hiArcSpeed = 1, 
        hiArcGravity = 1, 
        apRadius = 4.2, 
        apForce = 150, 
        heRadius = 4, 
        heForce = 60, 
        frForce = 140, 
        frForceMin = 30, 
        frRadius = 28, 
        frRadiusMin = 8, 
        maxTrackAngle = 0.017453292519943295, 
        avScale = 30, 
        reloadTime = 5, 
        carryMax = 12, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Premium", 
                range = 700, 
                apRadius = 5.9, 
                apForce = 189, 
                heRadius = 5.6, 
                heForce = 84, 
                frForce = 156.8, 
                frForceMin = 33.6, 
                frRadius = 31.4, 
                frRadiusMin = 9, 
                avScale = 40
            }, 
            {
                name = "LongRange", 
                range = 920, 
                loArcSpeed = 1280, 
                apRadius = 3.7, 
                apForce = 147, 
                heRadius = 3.5, 
                heForce = 52, 
                frForce = 121.8, 
                frForceMin = 26.1, 
                frRadius = 24.4, 
                frRadiusMin = 7, 
                avScale = 25
            }
        }
    }, 
    ["50Cal"] = {
        class = "50Cal", 
        type = "bullet", 
        protoBolt = v6("ProtoBullet"), 
        range = 750, 
        loArcSpeed = 1200, 
        loArcGravity = 40, 
        hiArcSpeed = 800, 
        hiArcGravity = 50, 
        apRadius = 0, 
        apForce = 80, 
        heRadius = 0, 
        heForce = 0, 
        frRadius = 0, 
        frForce = 40, 
        avScale = 30, 
        reloadTime = 0, 
        upgradeList = {}, 
        upgrades = {
            {
                name = "Auto", 
                reloadTime = 0.1, 
                avScale = 40
            }
        }
    }, 
    RifIe = {
        class = "RifIe", 
        type = "bullet", 
        protoBolt = v6("ProtoBullet"), 
        range = 800, 
        loArcSpeed = 850, 
        loArcGravity = 25, 
        hiArcSpeed = 500, 
        hiArcGravity = 50, 
        apRadius = 0, 
        apForce = 30, 
        heRadius = 0, 
        heForce = 0, 
        frRadius = 0, 
        frForce = 10, 
        avScale = 20, 
        reloadTime = 0.1, 
        carryMax = 120, 
        upgradeList = {}, 
        upgrades = {}
    }
}
